toc:
  - name: WELCOME
    file: welcome.md
  - name: Entry point
    file: entry-point.md
  - index
  - name: MISC
    description: Miscellaneous items
  - typedefs
  - extensions/uint8array
  - name: crypto
  - crypto/keys
