toc:
  - name: WELCOME
    file: welcome.md
  - name: CONFIGURATION
    file: configuration.md
  - config
  - name: ENTRY POINT
    file: entry-point.md
  - index
  - name: MISC
    description: Miscellaneous items
  - typedefs
  - extensions/uint8array
  - errors
  - util
  - name: CRYPTO
    file: crypto.md
  - crypto/util
  - crypto/keys
  - crypto/secret
  - crypto/public
  - crypto/sign
  - crypto/scrypt-proxy
  - name: STORAGE
  - TinyDb
  - StorageEngineInterface
  - NodeJsonStorage
  - name: UTILITY CLASSES
  - description: Shared classes for different purposes not related to business logic directly.
  - Queue
  - Clock
  - Timer
  - MRUList
  - ArrayStream
  - name: HELPERS
    description: Various kinds of helper modules
  - helpers/system-messages
  - helpers/file
  - helpers/string
  - helpers/retry
  - helpers/prombservable
  - helpers/dynamic-array-map
  - helpers/di-current-user
  - helpers/di-file-store
  - helpers/di-contact-store
  - helpers/field-validation
  - helpers/user-validators
  - name: NETWORK
  - socket
  - SocketClient
  - name: COMMON LOGIC
  - ClientApp
  - PhraseDictionary
  - ServerSettings
  - UpdateTracker
  - name: SYSTEM WARNINGS
    file: warnings.md
  - SystemWarning
  - ServerWarning
  - Warnings
  - name: USER
  - name: CONTACTS
  - name: CHATS
  - name: FILES
  - name: KEGS
  - name: LOCALIZATION

