# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
    working_directory: ~/repo
    steps:
      - checkout
      #
      # - run:
      #     name: "Update npm"
      #     command: |
      #       npm install npm@latest
      #       sudo rm -rf /usr/local/lib/node_modules/npm
      #       sudo mv node_modules/npm /usr/local/lib/node_modules/npm
      #       sudo chown -R 500:500 /usr/local/lib/node_modules/npm
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: eslint
          command: npm run code:verify
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    docker:
      - image: circleci/node:8.6
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
        fingerprints:
          - "15:67:d4:11:95:c0:e3:06:59:38:4a:16:05:fc:bd:11"
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: ./scripts/dev-release.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev

